my_string = input("Расскажите в какой сфере вы работаете? ")
print(my_string)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
